[package]
name = "graph_layout"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17.0"
yew = "0.18.0"
petgraph = "0.6.0"