[package]
name = "ipn_sim_bin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipn_sim_lib = { path = '../ipn_sim_lib' }

rand = { version = "0.8.4" }