on:
  push:
    branches:
      - master

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build web app
        run: |
          cd ipn_sim_web_app
          npm i
          npm run build

      - name: Build router zoo
        run: |
          cd router_zoo
          npm i
          npm run build

      - name: Move
        run: |
          mkdir pages_dist
          mv ipn_sim_web_app/dist pages_dist/web-app
          mv router_zoo/dist pages_dist/router-zoo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: pages_dist